ALTER DATABASE StreamingMovies SET ALLOW_SNAPSHOT_ISOLATION ON

WAITFOR DELAY '00:00:10'
BEGIN TRAN
	UPDATE Movies SET MovieTitle = 'Some title' WHERE MovieID = 1
	WAITFOR DELAY '00:00:10'
COMMIT TRAN

--ALTER DATABASE StreamingMovies SET ALLOW_SNAPSHOT_ISOLATION OFF
